### ISSUE TITLE
Missing addon

### ISSUE THREAD

**Issue by evUser1987** [VoltSim/VoltSim#12] opened 2022-04-14 07:50 UTC
I bought addon with dc motor but I can not use it. Pleas refound money.

**Comment by evUser1987** [comment] 2022-04-14 07:50
![mistake](https://user-images.githubusercontent.com/103630919/163339266-24fb77e3-c868-48a5-84c7-a3bdbd0528b2.png)

**Comment by voltsimapp** [comment] 2022-04-14 08:21
Hi @evUser1987, 
Looks like a bug, the motor shouldn't be rotated that way.  what extension did you buy? Was the motor rotated like that when you added it? can you please provide some steps to reproduce the issue?

If you wish to have a refund, please email voltsim.app@gmail.com with the extension you bought and the date when it was purchased. We will initiate the refund procedure.

**Comment by evUser1987** [comment] 2022-04-14 09:15
Yes, it was rotated. Chose motor from menu and add... there are bugs in app in projects list also... My order GPA.3369-7900-9211-56900

**Comment by evUser1987** [comment] 2022-04-14 09:28
![mistak2](https://user-images.githubusercontent.com/103630919/163356548-20ed26f6-fcc2-4a5f-82ac-615d0fbf1231.png)

**Comment by voltsimapp** [comment] 2022-04-14 11:22
Can you please provide the device model and os information? Are you running in a simulator?

**Comment by evUser1987** [comment] 2022-04-14 12:05
Samsung Galaxy J7 Android 7

**Comment by evUser1987** [comment] 2022-04-15 18:41
Do you have solution??

**Comment by voltsimapp** [comment] 2022-04-16 18:19
We are unable to reproduce this specific issue on our end. So we cannot propose a solution yet.

As mentioned earlier, please email voltsim.app@gmail.com for a refund. Github issues are used only for bugs/feature tracking.

**Comment by voltsimapp** [comment] 2022-06-08 07:17
closing as we couldnt reproduce the bug.

**Closed by voltsimapp** 2022-06-08 07:17 UTC
