### ISSUE TITLE
Multi select isdue

### ISSUE THREAD

**Issue by Biggidy** [VoltSim/VoltSim#82] opened 2024-09-04 08:50 UTC
When I multi select components it doesnt drag the lines/cables - they stay still despite being highlighted.

**Comment by voltsimapp** [comment] 2024-09-07 06:31
Hi, curently if you move components all the wires between them will move automatically. Are you trying to move just the wires? why not just connect them after moving? Can you show a screen recording of what you are trying to achieve?

**Comment by Biggidy** [comment] 2024-09-07 08:26
Hi,

Thanks for your response.

It is when I duplicate sections of a circuit or highlight large parts of a
circuit to move parts.

Please see video attached.


Kind regards


Damian

**Comment by voltsimapp** [comment] 2024-09-07 09:21
Hello,

It looks like you missed attaching video? If you have trouble attaching
video in github please send it to ***@***.***

**Comment by Biggidy** [comment] 2024-09-07 09:23
Please find attachment

https://github.com/user-attachments/assets/05154659-b167-458f-b3c2-765484103365

**Comment by voltsimapp** [comment] 2024-09-08 01:32
Thank you, that definitely looks like a bug and we can reproduce it. We will be fixing it in the next update.

It looks like the issue only happens when the simulator is stopped. If the simulator is running and you duplicate and move the components the wires also move with them. Can you confirm?

**Comment by Biggidy** [comment] 2024-09-08 02:43
Yes, that is correct, only when the simulation is stopped. 

Thanks for pointing it out, now I can work around the issue until the update 👍🏻

**Comment by voltsimapp** [comment] 2024-09-30 06:07
This bug is fixed in the latest update 0.2.16

**Closed by voltsimapp** 2024-09-30 06:07 UTC
Labels: bug, dev_completed
