### ISSUE TITLE
Delayer component

### ISSUE THREAD

**Issue by Unexian** [VoltSim/VoltSim#55] opened 2024-01-22 13:46 UTC
A digital component that adds a small delay to its input. Ig this could be created with a clock, but it's just easier to have it as its own component.

**Comment by voltsimapp** [comment] 2024-01-22 21:53
Hello, Thank you for your feedback. We will add a buffer with configurable delay. You can expect this in the next update.

**Comment by voltsimapp** [comment] 2024-05-02 07:12
Fixed in 0.2.13; Please reopen if the issue is still not resolved.

**Closed by voltsimapp** 2024-05-02 07:12 UTC
Labels: feature, next_update
