### ISSUE TITLE
Undo and Align buttons other way around?

### ISSUE THREAD

**Issue by marnovdm** [VoltSim/VoltSim#62] opened 2024-02-26 10:32 UTC
For mobile use I think it would make more sense to switch align and undo, so undo is more easily accessible (I think it's used way more often than the align toggle).

Right now on my Pixel 6 the align button is visible but I have to swipe to the side to get to undo.
![Screenshot_20240226-113017](https://github.com/VoltSim/VoltSim/assets/3329313/b02528c6-ae6a-4c64-9c3d-1900791979c8)

Perhaps Align makes more sense under Grid settings instead of as a separate button on the toolbar at the top.

**Comment by voltsimapp** [comment] 2024-05-02 07:09
Fixed in 0.2.13; Please reopen if the issue is still not resolved.

**Closed by voltsimapp** 2024-05-02 07:09 UTC
Labels: enhancement, next_update, dev_completed
