### ISSUE TITLE
add part

### ISSUE THREAD

**Issue by Sanjeebkr** [VoltSim/VoltSim#73] opened 2024-06-08 18:00 UTC
add bios chip and many parts missing

**Comment by Sanjeebkr** [comment] 2024-06-10 10:25
Ok know issue please make custom field to create ic according to me. I
eagerly waiting  that feature

**Comment by voltsimapp** [comment] 2024-08-17 07:17
Duplicate of https://github.com/VoltSim/VoltSim/issues/21

**Closed by voltsimapp** 2024-08-17 07:17 UTC
